[database]
# Os valores serão injetados via variáveis de ambiente no container
host = {{env "DB_HOST"}}
port = {{env "DB_PORT"}}
database = {{env "DB_NAME"}}
user = {{env "DB_USER"}}
password = {{env "DB_PASSWORD"}}

[data]
# Variáveis customizadas para os templates SQL
